CREATE DATABASE email;

\c email

CREATE TABLE email(
  id SERIAL PRIMARY KEY,
  email VARCHAR(100) UNIQUE NOT NULL,
  rubro VARCHAR(100) NOT NULL,
  fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  send BOOLEAN DEFAULT false
);